quarkus.index-dependency.langchain4j-mcp-common.group-id=dev.langchain4j.cdi.mcp
quarkus.index-dependency.langchain4j-mcp-common.artifact-id=langchain4j-cdi-mcp-integration-tests-common

quarkus.index-dependency.langchain4j-mcp-server.group-id=dev.langchain4j.cdi.mcp
quarkus.index-dependency.langchain4j-mcp-server.artifact-id=langchain4j-cdi-mcp-server

# Prevent ArC from removing @Tool beans that are not directly injected
quarkus.arc.remove-unused-beans=false

quarkus.http.port=-1
quarkus.http.test-port=-1
